# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Kris Michael D Silva
description: "A problem solving, math loving, results-oriented Data Scientist with a strong passion for mathematics, having 5 years of experience in designing and implementing data-driven solutions in finance and cybersecurity industries. Proven track record of success in portfolio analysis, anomaly detection and pattern recognition by leveraging a versatile skill set to generate actionable insights and drive business growth."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Dublin, IE"
resume_url: /docs/resume.pdf
avatar_image: /img/profile_picture.jpg

#-------------------------------
# Contact links
linkedln: "https://linkedln.com/in/kris-michael-d-silva-3307/" # Add your linkedln handle
github: "https://github.com/Kris3317"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

